### ISSUE TITLE
Remove the need of the dos2unix program

### ISSUE THREAD

**Issue by mikygee** [Cacti/spine#164]
Spine: 1.2.13

Hello,
It would be nice if you removed the need to use dos2unix

I don't want to install this program on my system and on the other hand there is no need for it when I download the tar.gz

Options possible:
- Remove the dos2unix
- Make a switch -nodos2unix or something like that which would disable the need for this program
- Add some code that would convert all lines ending by \r\n with \n and remove the need for dos2unix

The latest option seems good.

Thank you

**Comment by netniV** [comment]
Does spine use this itself? I will have to check.  It may be used by third party scripts.

**Comment by mikygee** [comment]
Hello, It's in the INSTALL file
```
6. Once on the package selection section make sure to select the following (TIP: use the search!):
      * dos2unix
```

And the bootstrap
```
# Check for dos2unix
which dos2unix > /dev/null 2>&1
[ $? -gt 0 ] && echo "FATAL: Unable to locate dos2unix utility" && exit -1
```

I'm downloading the cacti-spine-1.2.13.tar.gz from the site to a unix platform so the file is correctly formatted.

I think bootstrap should test if it's a windows platform, if yes make the dos2unix program a prerequisite, else skip the dos2unix presence verification.

**Comment by mikygee** [comment]
In bootstrap I modified the code like this
unamestr=$(uname)

```
if [ $unamestr != 'OpenBSD' ]; then
  # Check for dos2unix
  which dos2unix > /dev/null 2>&1
  [ $? -gt 0 ] && echo "FATAL: Unable to locate dos2unix utility" && exit -1
  find . -type f -exec dos2unix --d2u \{\} \; > /dev/null 2>&1
fi
```

Honestly, this dos2unix command is just usefull when you're on a Windows platform so the condition should be something like
`if [ $unamestr == 'Windows' ]; then`

If you're on mac or linux you can assume that \r\n won't be added during the download.

**Comment by netniV** [comment]
That does seem reasonable.  I guess the precaution is there in case we actually package on a windows system.  It may even really be a hang over from the SVN days because SVN used to convert line feeds.  I don't think that Windows should actually convert the files imho, so we might be better removing it altogether, what do you think @TheWitness, @cigamit or @browniebraun ?

**Comment by cigamit** [comment]
While I don't think "I don't want to install this program on my system" is a valid reason for removing it, I don't believe it has been required on the Linux side since we moved to git.  I tested it on Centos last night and didn't have any issues.  I would wait until we get feedback from the Windows side though.

**Comment by netniV** [comment]
> I don't think "I don't want to install this program on my system" is a valid reason for removing it

That was my first thought and I would agree with that sentiment, though if it's unneeded then removing unnecessary prerequisites is always a good thing in my book 👍

**Comment by TheWitness** [comment]
dos2unix is everywhere.  I use it all the time.  The need for this was due to a legacy, and still relevant today of people who are still performing development and merge activities on Windows and those who prefer just to use the GitHub Desktop.

Unfortunately, decades ago, Microsoft decided to make the backslash character a directory separator, and thus began a multi-decade long path of incompatibility that continues today.  To add insult to injury, they also had to adopt the Carriage Return (yea, for old guys like me, that was the arm on the manual typewriter that you had to pull to go from the end of a line to the next one).  Oh well, I thought I would write this down just in case the new kiddies were wondering what the hell happened in the late 70's and early 80's.

**Comment by netniV** [comment]
Drugs

**Comment by TheWitness** [comment]
The more I use windows, and I use it every day, the more I dislike it.  But could not work without unless, I do.

**Comment by mikygee** [comment]
Hello TheWitness,
I think the idea would be to have a switch for Windows
```
unamestr=$(uname)
if [ $unamestr == 'Windows' ]; then
  # Check for dos2unix
  which dos2unix > /dev/null 2>&1
  [ $? -gt 0 ] && echo "FATAL: Unable to locate dos2unix utility" && exit -1
  find . -type f -exec dos2unix --d2u \{\} \; > /dev/null 2>&1
fi
```
I'm not sure about what gives unamestr=$(uname) on Windows, can you test it ?
Would you consider implement this code ?

When users are on Linux/Unix only there is no reason why a \r\n would appear, except if they download the cacti on their Windows desktop, unzip it, open a file and save it with notepad and then reupload it on a linux machine.
