### ISSUE TITLE
Bootstrap corrupts binary files

### ISSUE THREAD

**Issue by netniV** [Cacti/spine#255]
**Describe the bug**
Bootstrap seems to be finding all files and ensuring that they are in UNIX format.  This corrupts any binary files that may be under the same directory.

**To Reproduce**
1. git clone https://github.com/cacti/spine spine
2. cd spine
3. ./bootstrap
4. git status

**Expected behavior**
Bootstrap should only be converting files that are required not all files regardless of their nature.

**Comment by TheWitness** [comment]
Let me take a shameless crack at it.

**Comment by TheWitness** [comment]
See with the latest if it's still corrupting things.

**Comment by netniV** [comment]
I did a minor update in 43efbf3 but if you think there are too many extensions now, let me know.

**Comment by TheWitness** [comment]
It was always just *.sh that blew up the auto-tools when trying to build on Cygwin.  This was primarily due to some of us older folks still using crap Windows based editor that insisted on CR-LF, and who used tools like WinSCP that insisted that *.sh, *.c, and *.h were DOS files and therefore converted to CR's.  I have this joke about the backslash and forward slash that I think I've told before.

You know, at one point in time, the directory did not exist in DOS.  It was like in version 1.x or so.  Then, Bill and his buddies said something like "hey UNIX uses directories, why don't we do that"?  Great idea, but the forward slash was already used by DOS to pass arguments, so they had to use the backslash.  That one decision, to use the backslash instead, turned UNIX into Water, and DOS/Windoz... Into Vinegar for decades to some.
