### ISSUE TITLE
When using Ping or SNMP Uptime, host is not always detected properly

### ISSUE THREAD

**Issue by TheWitness** [Cacti/spine#350]
**Describe the bug**

Spine, in the latest develop, does not handle "Ping or SNMP Uptime" properly resulting in missed down hosts.

**Expected behavior**

Spine should handle these cases properly.

**Comment by madimsz** [comment]
I have the same issue with spine on 3 different instances, cmd gives correct behavior.

Cacti Version 1.2.25
SPINE Version 1.2.25

![image](https://github.com/Cacti/spine/assets/167423607/354bc4fe-1837-4577-8d3f-b45257cbed7b)

**Comment by TheWitness** [comment]
@madimsz, What was your PING method?

**Comment by xxconn** [comment]
I have found the Version 1.2.30 has the same issue.

// My lab devices look like the following:
<img width="749" height="66" alt="Image" src="https://github.com/user-attachments/assets/a0df8b96-86ab-496e-afdf-b6c1f8628c6f" />

// Device (10.1.1.1 with Ping AND Snmp) spine debug log:
# spine -f 3999 -l 4000 -V 5 -S
SPINE: Using spine config file [/etc/spine.conf]
Total[0.0013] DEBUG: The path_php_server variable is /var/www/cacti/script_server.php
Total[0.0013] DEBUG: The path_cactilog variable is /var/www/cacti/log/cacti.log
Total[0.0013] DEBUG: The version variable is 10.11.10-MariaDB
Total[0.0013] DEBUG: The log_destination variable is 4 (STDOUT)
Total[0.0014] DEBUG: The path_php variable is /usr/bin/php
Total[0.0014] DEBUG: The availability_method variable is 4
Total[0.0014] DEBUG: The ping_recovery_count variable is 2
Total[0.0015] DEBUG: The ping_failure_count variable is 2
Total[0.0015] DEBUG: The ping_method variable is 1
Total[0.0015] DEBUG: The ping_retries variable is 3
Total[0.0015] DEBUG: The ping_timeout variable is 2000
Total[0.0016] DEBUG: The snmp_retries variable is 3
Total[0.0016] DEBUG: The log_perror variable is 1
Total[0.0017] DEBUG: The log_pwarn variable is 0
Total[0.0017] DEBUG: The boost_redirect variable is 1
Total[0.0017] DEBUG: The boost_rrd_update_enable variable is 1
Total[0.0017] DEBUG: The log_pstats variable is 0
Total[0.0018] DEBUG: The threads variable is 15
Total[0.0018] DEBUG: The polling interval is 60 seconds
Total[0.0018] DEBUG: The number of concurrent processes is 4
Total[0.0019] DEBUG: The script timeout is 60
Total[0.0019] DEBUG: The selective_device_debug variable is
Total[0.0019] DEBUG: The spine_log_level variable is 0
Total[0.0019] DEBUG: The number of php script servers to run is 2
Total[0.0020] DEBUG: The number of active data source profiles is 1
Total[0.0020] DEBUG: The number of snmp ports on the system is 1
Total[0.0021] DEBUG: StartDevice='3999', EndDevice='4000', TotalPHPScripts='0'
Total[0.0021] DEBUG: The PHP Script Server is Not Required
Total[0.0021] DEBUG: The Maximum SNMP OID Get Size is 10
Total[0.0022] DEBUG: Total Connections made 1
Total[0.0022] DEBUG: Creating Local Connection Pool of 15 threads.
Total[0.0022] DEBUG: Creating Local Connection 0.
Total[0.0023] DEBUG: Total Connections made 2
Total[0.0025] DEBUG: Creating Local Connection 1.
Total[0.0026] DEBUG: Total Connections made 3
Total[0.0028] DEBUG: Creating Local Connection 2.
Total[0.0029] DEBUG: Total Connections made 4
Total[0.0030] DEBUG: Creating Local Connection 3.
Total[0.0031] DEBUG: Total Connections made 5
Total[0.0033] DEBUG: Creating Local Connection 4.
Total[0.0034] DEBUG: Total Connections made 6
Total[0.0036] DEBUG: Creating Local Connection 5.
Total[0.0037] DEBUG: Total Connections made 7
Total[0.0038] DEBUG: Creating Local Connection 6.
Total[0.0039] DEBUG: Total Connections made 8
Total[0.0041] DEBUG: Creating Local Connection 7.
Total[0.0042] DEBUG: Total Connections made 9
Total[0.0043] DEBUG: Creating Local Connection 8.
Total[0.0044] DEBUG: Total Connections made 10
Total[0.0046] DEBUG: Creating Local Connection 9.
Total[0.0047] DEBUG: Total Connections made 11
Total[0.0049] DEBUG: Creating Local Connection 10.
Total[0.0050] DEBUG: Total Connections made 12
Total[0.0052] DEBUG: Creating Local Connection 11.
Total[0.0053] DEBUG: Total Connections made 13
Total[0.0055] DEBUG: Creating Local Connection 12.
Total[0.0056] DEBUG: Total Connections made 14
Total[0.0057] DEBUG: Creating Local Connection 13.
Total[0.0058] DEBUG: Total Connections made 15
Total[0.0060] DEBUG: Creating Local Connection 14.
Total[0.0060] DEBUG: Total Connections made 16
Total[0.0063] DEBUG: Version 1.2.30 starting
Total[0.0063] No Device 0 Poller Items found.
Total[0.0063] DEBUG: MySQL is Thread Safe!
Total[0.0063] DEBUG: Spine running as 0 UID, 0 EUID
Total[0.0063] DEBUG: Spine is running as root.
Total[0.0063] DEBUG: Spine has got ICMP
Total[0.0063] DEBUG: Initializing Net-SNMP API
Total[0.0063] DEBUG: Issues with SNMP Header Version information, assuming old version of Net-SNMP.
Total[0.0076] DEBUG: Initializing PHP Script Server(s)
Total[0.0082] DEBUG: Initial Value of Available Threads is 15 (0 outstanding)
Total[0.0083] DEBUG: Device[3999] Valid Thread to be Created (139879643784768)
Total[0.0083] DEBUG: Device[3999] Available Threads is 14 (1 outstanding)
Total[0.0084] DEBUG: Device[3999] HT[1] In Poller, About to Start Polling
Total[0.0084] DEBUG: Traversing Local Connection Pool for free connection.
Total[0.0084] DEBUG: Checking Local Pool ID 0.
Total[0.0084] DEBUG: Allocating Local Pool ID 0.
Total[0.0084] DEBUG: Device[4000] Valid Thread to be Created (139879635392064)
Total[0.0084] DEBUG: Device[4000] Available Threads is 13 (2 outstanding)
Total[0.0084] NOTE: Polling sleeping while waiting for 2 Threads to End
Total[0.0085] DEBUG: Device[4000] HT[1] In Poller, About to Start Polling
Total[0.0085] DEBUG: Traversing Local Connection Pool for free connection.
Total[0.0085] DEBUG: Checking Local Pool ID 0.
Total[0.0085] DEBUG: Checking Local Pool ID 1.
Total[0.0085] DEBUG: Allocating Local Pool ID 1.
Total[0.0086] DEBUG: get_namebyhost(10.1.1.1) - Allocating name_t
Total[0.0086] DEBUG: get_namebyhost(10.1.1.1) - No delimiter, assume full hostname
Total[0.0086] Device[3999] INFO: SNMP Device '10.1.1.1:161' has a timeout of 2000000 (2000), with 3 retries
Total[0.0086] DEBUG: get_namebyhost(10.1.1.2) - Allocating name_t
Total[0.0086] DEBUG: get_namebyhost(10.1.1.2) - No delimiter, assume full hostname
Total[0.0086] Device[4000] INFO: SNMP Device '10.1.1.2:161' has a timeout of 2000000 (2000), with 3 retries
Total[0.0086] Device[3999] IPv4 address 10.1.1.1 (10.1.1.1)
Total[0.0087] DEBUG: Device[3999] Entering ICMP Ping
Total[0.0087] NOTE: Polling sleeping while waiting for 2 Threads to End
Total[0.0087] Device[4000] IPv4 address 10.1.1.2 (10.1.1.2)
Total[0.0087] DEBUG: Device[4000] Entering ICMP Ping
Total[0.0087] NOTE: Polling sleeping while waiting for 2 Threads to End
Total[0.0087] DEBUG: Device[3999] Attempting to ping 10.1.1.1, seq 0 (Retry 0 of 3)
Total[0.0087] NOTE: Polling sleeping while waiting for 2 Threads to End
Total[0.0087] NOTE: Polling sleeping while waiting for 2 Threads to End
Total[0.0087] DEBUG: Device[4000] Attempting to ping 10.1.1.2, seq 1 (Retry 0 of 3)
Total[0.5088] NOTE: Polling sleeping while waiting for 2 Threads to End
Total[1.0088] NOTE: Polling sleeping while waiting for 2 Threads to End
Total[1.5089] NOTE: Polling sleeping while waiting for 2 Threads to End
Total[2.0090] NOTE: Polling sleeping while waiting for 2 Threads to End
Total[2.0108] DEBUG: Device[4000] Exceeded Device Timeout, Retrying
Total[2.0118] DEBUG: Device[4000] Attempting to ping 10.1.1.2, seq 1 (Retry 1 of 3)
Total[2.0119] DEBUG: Device[3999] Exceeded Device Timeout, Retrying
Total[2.0130] DEBUG: Device[3999] Attempting to ping 10.1.1.1, seq 0 (Retry 1 of 3)
Total[2.5090] NOTE: Polling sleeping while waiting for 2 Threads to End
Total[3.0091] NOTE: Polling sleeping while waiting for 2 Threads to End
Total[3.5091] NOTE: Polling sleeping while waiting for 2 Threads to End
Total[4.0092] NOTE: Polling sleeping while waiting for 2 Threads to End
Total[4.0138] DEBUG: Device[4000] Exceeded Device Timeout, Retrying
Total[4.0149] DEBUG: Device[4000] Attempting to ping 10.1.1.2, seq 1 (Retry 2 of 3)
Total[4.0150] DEBUG: Device[3999] Exceeded Device Timeout, Retrying
Total[4.0160] DEBUG: Device[3999] Attempting to ping 10.1.1.1, seq 0 (Retry 2 of 3)
Total[4.5093] NOTE: Polling sleeping while waiting for 2 Threads to End
Total[5.0093] NOTE: Polling sleeping while waiting for 2 Threads to End
Total[5.5094] NOTE: Polling sleeping while waiting for 2 Threads to End
Total[6.0094] NOTE: Polling sleeping while waiting for 2 Threads to End
Total[6.0169] DEBUG: Device[4000] Exceeded Device Timeout, Retrying
Total[6.0179] DEBUG: Device[4000] Attempting to ping 10.1.1.2, seq 1 (Retry 3 of 3)
Total[6.0181] DEBUG: Device[3999] Exceeded Device Timeout, Retrying
Total[6.0191] DEBUG: Device[3999] Attempting to ping 10.1.1.1, seq 0 (Retry 3 of 3)
Total[6.5095] NOTE: Polling sleeping while waiting for 2 Threads to End
Total[7.0096] NOTE: Polling sleeping while waiting for 2 Threads to End
Total[7.5096] NOTE: Polling sleeping while waiting for 2 Threads to End
Total[8.0097] NOTE: Polling sleeping while waiting for 2 Threads to End
Total[8.0199] DEBUG: Device[4000] Exceeded Device Timeout, Retrying
Total[8.0210] Device[4000] PING Result: ICMP: Ping timed out
Total[8.0210] Device[4000] SNMP Result: SNMP not performed due to setting or ping result
Total[8.0211] DEBUG: Device[3999] Exceeded Device Timeout, Retrying
Total[8.0213] Device[4000] HT[1] Device has no information for recache.
Total[8.0214] Device[4000] HT[1] Total Time: 8 Seconds
Total[8.0214] DEBUG: Freeing Local Pool ID 1
Total[8.0214] DEBUG: Device[4000] HT[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
Total[8.0222] Device[3999] PING Result: ICMP: Ping timed out
Total[8.0222] Device[3999] SNMP Result: SNMP not performed due to setting or ping result
Total[8.0225] Device[3999] HT[1] Total Time: 8 Seconds
Total[8.0225] DEBUG: Freeing Local Pool ID 0
Total[8.0225] DEBUG: Device[3999] HT[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
Total[8.5097] The final count of Threads is 0
Total[8.5097] INFO: Device[3999] Thread complete and 0 to 0 sources
Total[8.5097] INFO: Device[4000] Thread complete and 0 to 0 sources
Total[8.5099] DEBUG: Closing Local Connection Pool ID 0
Total[8.5099] DEBUG: Closing Local Connection Pool ID 1
Total[8.5099] DEBUG: Closing Local Connection Pool ID 2
Total[8.5099] DEBUG: Closing Local Connection Pool ID 3
Total[8.5099] DEBUG: Closing Local Connection Pool ID 4
Total[8.5099] DEBUG: Closing Local Connection Pool ID 5
Total[8.5099] DEBUG: Closing Local Connection Pool ID 6
Total[8.5099] DEBUG: Closing Local Connection Pool ID 7
Total[8.5100] DEBUG: Closing Local Connection Pool ID 8
Total[8.5100] DEBUG: Closing Local Connection Pool ID 9
Total[8.5100] DEBUG: Closing Local Connection Pool ID 10
Total[8.5100] DEBUG: Closing Local Connection Pool ID 11
Total[8.5100] DEBUG: Closing Local Connection Pool ID 12
Total[8.5100] DEBUG: Closing Local Connection Pool ID 13
Total[8.5100] DEBUG: Closing Local Connection Pool ID 14
Total[8.5100] DEBUG: Thread Cleanup Complete
Total[8.5100] DEBUG: PHP Script Server Pipes Closed
Total[8.5100] DEBUG: Allocated Variable Memory Freed
Total[8.5100] DEBUG: MYSQL Free & Close Completed
Total[8.5100] DEBUG: Net-SNMP Close Completed
Total[8.5100] Time: 8.5100 s, Threads: 15, Devices: 2

// Device (10.1.1.2 with Ping OR Snmp) spine debug log:
# spine -f 4000 -l 4001 -V 5 -S
SPINE: Using spine config file [/etc/spine.conf]
Total[0.0014] DEBUG: The path_php_server variable is /var/www/cacti/script_server.php
Total[0.0014] DEBUG: The path_cactilog variable is /var/www/cacti/log/cacti.log
Total[0.0014] DEBUG: The version variable is 10.11.10-MariaDB
Total[0.0014] DEBUG: The log_destination variable is 4 (STDOUT)
Total[0.0014] DEBUG: The path_php variable is /usr/bin/php
Total[0.0015] DEBUG: The availability_method variable is 4
Total[0.0015] DEBUG: The ping_recovery_count variable is 2
Total[0.0015] DEBUG: The ping_failure_count variable is 2
Total[0.0015] DEBUG: The ping_method variable is 1
Total[0.0016] DEBUG: The ping_retries variable is 3
Total[0.0016] DEBUG: The ping_timeout variable is 2000
Total[0.0016] DEBUG: The snmp_retries variable is 3
Total[0.0016] DEBUG: The log_perror variable is 1
Total[0.0017] DEBUG: The log_pwarn variable is 0
Total[0.0017] DEBUG: The boost_redirect variable is 1
Total[0.0017] DEBUG: The boost_rrd_update_enable variable is 1
Total[0.0018] DEBUG: The log_pstats variable is 0
Total[0.0018] DEBUG: The threads variable is 15
Total[0.0018] DEBUG: The polling interval is 60 seconds
Total[0.0019] DEBUG: The number of concurrent processes is 4
Total[0.0019] DEBUG: The script timeout is 60
Total[0.0019] DEBUG: The selective_device_debug variable is
Total[0.0019] DEBUG: The spine_log_level variable is 0
Total[0.0020] DEBUG: The number of php script servers to run is 2
Total[0.0020] DEBUG: The number of active data source profiles is 1
Total[0.0020] DEBUG: The number of snmp ports on the system is 1
Total[0.0021] DEBUG: StartDevice='4000', EndDevice='4001', TotalPHPScripts='0'
Total[0.0021] DEBUG: The PHP Script Server is Not Required
Total[0.0021] DEBUG: The Maximum SNMP OID Get Size is 10
Total[0.0023] DEBUG: Total Connections made 1
Total[0.0023] DEBUG: Creating Local Connection Pool of 15 threads.
Total[0.0023] DEBUG: Creating Local Connection 0.
Total[0.0025] DEBUG: Total Connections made 2
Total[0.0027] DEBUG: Creating Local Connection 1.
Total[0.0029] DEBUG: Total Connections made 3
Total[0.0032] DEBUG: Creating Local Connection 2.
Total[0.0033] DEBUG: Total Connections made 4
Total[0.0035] DEBUG: Creating Local Connection 3.
Total[0.0036] DEBUG: Total Connections made 5
Total[0.0038] DEBUG: Creating Local Connection 4.
Total[0.0040] DEBUG: Total Connections made 6
Total[0.0042] DEBUG: Creating Local Connection 5.
Total[0.0043] DEBUG: Total Connections made 7
Total[0.0045] DEBUG: Creating Local Connection 6.
Total[0.0046] DEBUG: Total Connections made 8
Total[0.0048] DEBUG: Creating Local Connection 7.
Total[0.0049] DEBUG: Total Connections made 9
Total[0.0050] DEBUG: Creating Local Connection 8.
Total[0.0051] DEBUG: Total Connections made 10
Total[0.0053] DEBUG: Creating Local Connection 9.
Total[0.0053] DEBUG: Total Connections made 11
Total[0.0055] DEBUG: Creating Local Connection 10.
Total[0.0056] DEBUG: Total Connections made 12
Total[0.0058] DEBUG: Creating Local Connection 11.
Total[0.0059] DEBUG: Total Connections made 13
Total[0.0061] DEBUG: Creating Local Connection 12.
Total[0.0062] DEBUG: Total Connections made 14
Total[0.0063] DEBUG: Creating Local Connection 13.
Total[0.0065] DEBUG: Total Connections made 15
Total[0.0067] DEBUG: Creating Local Connection 14.
Total[0.0068] DEBUG: Total Connections made 16
Total[0.0070] DEBUG: Version 1.2.30 starting
Total[0.0070] No Device 0 Poller Items found.
Total[0.0071] DEBUG: MySQL is Thread Safe!
Total[0.0071] DEBUG: Spine running as 0 UID, 0 EUID
Total[0.0071] DEBUG: Spine is running as root.
Total[0.0071] DEBUG: Spine has got ICMP
Total[0.0071] DEBUG: Initializing Net-SNMP API
Total[0.0071] DEBUG: Issues with SNMP Header Version information, assuming old version of Net-SNMP.
Total[0.0084] DEBUG: Initializing PHP Script Server(s)
Total[0.0091] DEBUG: Initial Value of Available Threads is 15 (0 outstanding)
Total[0.0092] DEBUG: Device[4000] Valid Thread to be Created (140313779414592)
Total[0.0092] DEBUG: Device[4000] Available Threads is 14 (1 outstanding)
Total[0.0092] NOTE: Polling sleeping while waiting for 1 Threads to End
Total[0.0092] DEBUG: Device[4000] HT[1] In Poller, About to Start Polling
Total[0.0093] DEBUG: Traversing Local Connection Pool for free connection.
Total[0.0093] DEBUG: Checking Local Pool ID 0.
Total[0.0093] DEBUG: Allocating Local Pool ID 0.
Total[0.0095] DEBUG: get_namebyhost(10.1.1.2) - Allocating name_t
Total[0.0095] DEBUG: get_namebyhost(10.1.1.2) - No delimiter, assume full hostname
Total[0.0095] Device[4000] INFO: SNMP Device '10.1.1.2:161' has a timeout of 2000000 (2000), with 3 retries
Total[0.0096] Device[4000] IPv4 address 10.1.1.2 (10.1.1.2)
Total[0.0096] DEBUG: Device[4000] Entering ICMP Ping
Total[0.0096] NOTE: Polling sleeping while waiting for 1 Threads to End
Total[0.0096] NOTE: Polling sleeping while waiting for 1 Threads to End
Total[0.0096] DEBUG: Device[4000] Attempting to ping 10.1.1.2, seq 0 (Retry 0 of 3)
Total[0.5097] NOTE: Polling sleeping while waiting for 1 Threads to End
Total[1.0097] NOTE: Polling sleeping while waiting for 1 Threads to End
Total[1.5098] NOTE: Polling sleeping while waiting for 1 Threads to End
Total[2.0099] NOTE: Polling sleeping while waiting for 1 Threads to End
Total[2.0117] DEBUG: Device[4000] Exceeded Device Timeout, Retrying
Total[2.0127] DEBUG: Device[4000] Attempting to ping 10.1.1.2, seq 0 (Retry 1 of 3)
Total[2.5099] NOTE: Polling sleeping while waiting for 1 Threads to End
Total[3.0100] NOTE: Polling sleeping while waiting for 1 Threads to End
Total[3.5100] NOTE: Polling sleeping while waiting for 1 Threads to End
Total[4.0101] NOTE: Polling sleeping while waiting for 1 Threads to End
Total[4.0140] DEBUG: Device[4000] Exceeded Device Timeout, Retrying
Total[4.0150] DEBUG: Device[4000] Attempting to ping 10.1.1.2, seq 0 (Retry 2 of 3)
Total[4.5102] NOTE: Polling sleeping while waiting for 1 Threads to End
Total[5.0103] NOTE: Polling sleeping while waiting for 1 Threads to End
Total[5.5104] NOTE: Polling sleeping while waiting for 1 Threads to End
Total[6.0104] NOTE: Polling sleeping while waiting for 1 Threads to End
Total[6.0171] DEBUG: Device[4000] Exceeded Device Timeout, Retrying
Total[6.0181] DEBUG: Device[4000] Attempting to ping 10.1.1.2, seq 0 (Retry 3 of 3)
Total[6.5105] NOTE: Polling sleeping while waiting for 1 Threads to End
Total[7.0106] NOTE: Polling sleeping while waiting for 1 Threads to End
Total[7.5107] NOTE: Polling sleeping while waiting for 1 Threads to End
Total[8.0107] NOTE: Polling sleeping while waiting for 1 Threads to End
Total[8.0201] DEBUG: Device[4000] Exceeded Device Timeout, Retrying
Total[8.0212] Device[4000] PING Result: ICMP: Ping timed out
Total[8.0212] Device[4000] SNMP Result: SNMP not performed due to setting or ping result
Total[8.0215] Device[4000] HT[1] Device has no information for recache.
Total[8.0216] Device[4000] HT[1] Total Time: 8 Seconds
Total[8.0217] DEBUG: Freeing Local Pool ID 0
Total[8.0217] DEBUG: Device[4000] HT[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
Total[8.5108] The final count of Threads is 0
Total[8.5108] INFO: Device[4000] Thread complete and 0 to 0 sources
Total[8.5110] DEBUG: Closing Local Connection Pool ID 0
Total[8.5110] DEBUG: Closing Local Connection Pool ID 1
Total[8.5110] DEBUG: Closing Local Connection Pool ID 2
Total[8.5110] DEBUG: Closing Local Connection Pool ID 3
Total[8.5110] DEBUG: Closing Local Connection Pool ID 4
Total[8.5110] DEBUG: Closing Local Connection Pool ID 5
Total[8.5110] DEBUG: Closing Local Connection Pool ID 6
Total[8.5110] DEBUG: Closing Local Connection Pool ID 7
Total[8.5111] DEBUG: Closing Local Connection Pool ID 8
Total[8.5111] DEBUG: Closing Local Connection Pool ID 9
Total[8.5111] DEBUG: Closing Local Connection Pool ID 10
Total[8.5111] DEBUG: Closing Local Connection Pool ID 11
Total[8.5111] DEBUG: Closing Local Connection Pool ID 12
Total[8.5111] DEBUG: Closing Local Connection Pool ID 13
Total[8.5111] DEBUG: Closing Local Connection Pool ID 14
Total[8.5111] DEBUG: Thread Cleanup Complete
Total[8.5111] DEBUG: PHP Script Server Pipes Closed
Total[8.5111] DEBUG: Allocated Variable Memory Freed
Total[8.5111] DEBUG: MYSQL Free & Close Completed
Total[8.5112] DEBUG: Net-SNMP Close Completed
Total[8.5112] Time: 8.5111 s, Threads: 15, Devices: 1
