### ISSUE TITLE
Spine Ping Error: Unknown error

### ISSUE THREAD

**Issue by interduo** [Cacti/spine#38]
2017-12-04 15:45:17 - SPINE: Poller[1] Device[DGS-1248] SNMP Ping Error: Unknown error: 2.
How to debug that?

If I change poller to PHP everything is allright.

**Comment by netniV** [comment]
If ping does not receive any reply packets at all it will exit with code 1. If a packet count and deadline are both specified, and fewer than count packets are received by the time the deadline has arrived, it will also exit with code 1.  On other error it exits with code 2. Otherwise it exits with code 0. This makes it possible to use the exit code to see if a host is alive or not.

**Comment by interduo** [comment]
1. This error is reproducable. If I change to PHP poller - no errors. 

2. I don't know is it connected by after changing to SPINE there are sometimes also UP/DOWN state changes notofications the destination host is always online. I set SNMP Timeout to 4000 but there is no effect.

**Comment by netniV** [comment]
This would suggest that spine is having an error querying DGS-1248 for SNMP and the error -2 which (according to net-snmp's snmp_api.h) is SNMPERR_BAD_LOCPORT.

> **SNMPERR_BAD_LOCPORT.**
> _The local port was bad because it had already been allocated or permission was denied._

This suggests that the local port spine tried to use for SNMP binding was already in use and therefore could not be used to contact the remote server.  In theory, if this error is received, the next port should be tried if it is increment through local ports.  If it is reusing the same port, it may not be being freed properly for some reason.

I would have to take another look tomorrow to see what the situation is if I have time.  But I'm not a spine expert :)

**Comment by interduo** [comment]
This don't exist when poller is set to PHP. Spine is obviousness when datasources >10k. It takes about 20sec when PHP poller takes about 160sec on my hardware.

**Comment by netniV** [comment]
Can you tell me what the availability method you have set for that host is?
None, SNMP, SNMP and PING, SNMP or PING, PING ?

**Comment by interduo** [comment]
I always set "Downed device detection to" SNMP Uptime and UDP Ping.

**Comment by netniV** [comment]
Could you add the device in question to the Device Debug section of settings.  See whether anything else pops up?

**Comment by netniV** [comment]
After another review of this issue, I realised that because you are using AVAIL_SNMP_AND_PING (in the spine world), the error is more than likely coming from the ping_snmp() function.  This function uses snmp_get() with an oid of .1.3.6.1.2.1.1.3.0 to check that the host in question is up.

As you are getting error 2 (not -2 as I original read, my bad) then this points to an authentication error being returned by snmp_get().  If you enable device debugging for the device mentioned above, this will be show more logs for that specific device.  Can you put a copy of those here, mask what may be sensitive.

On the back of this, would I be right in assuming that you are using SNMP v3? If so, this would suggest that something is going wrong with the authentication logic which is beyond me at the moment.  I can try and compare the PHP code with the C code but it'd be quite easy for me to miss something.

Once you paste the logs, I can probably confirm or deny this theory.

**Comment by interduo** [comment]
I have a cauldron in work this day.

I set the debug for some specified devices but out of spite there is no errors for this devices now (but there are some up/down flaps for others whitch I add to debug selective list if it occurs...). The same situation - device is avaible from ping/web but cacti using spine show flaps.

Also I set ping_timeout to 4000 and ping_retries = 3 for all of problematic devices.

**Comment by netniV** [comment]
The chances are you are having a problem with both the UDP Ping and the SNMP Uptime.  Because it's timing out, it's causing the authentication error 2 more than likely, since it can't actually authenticate.

**Comment by cigamit** [comment]
Those errors were actually snmp timeout errors.  This issue is now resolved.

**Comment by interduo** [comment]
Thanks!

**Comment by netniV** [comment]
Would it be worth putting the error number on the unknown error log?

**Comment by cigamit** [comment]
That function call has three return values.  Basically OK, TIMEOUT, ERROR.  Oddly enough, when I audited the function call, we were using the Net-SNMP Error message API incorrectly.  So, error 2 was just a timeout.
