### ISSUE TITLE
Availability check none triggers snmp system check that causes device to be ignored

### ISSUE THREAD

**Issue by feisenko** [Cacti/spine#48]
This behavior is different from cmd.php and spine 0.8.x. and also not logical.
Background: the Device SNMP information are set because they are correct for this device, but at the moment SNMP and PING is blocked by an other device in the network path and only HTTP access is possible, which is queried via PHP Script Server.

Proposed solution to restore previous behavior:
poller.c (Version 1.1.34) Line 544: if (host->availability_method != AVAIL_PING) {
needs to be changed to:
if ((host->availability_method != AVAIL_PING) && (host->availability_method != AVAIL_NONE)) {
so that get_system_information is not called, which is setting ignore_host to TRUE (in snmp.c line: 379) if the device does not respond to SNMP requests.

Remark: this issue is moved from the cacti repo to the spine repo:  https://github.com/Cacti/cacti/issues/1324

Best regards,
Franz

**Comment by netniV** [comment]
So this is my assessment of the code based on what you have provided above, but i'm not expert on spine.

The ignore_host flag gets used to determine whether or not to reindex the SNMP data that it has for a given host. The method get_system_information() itself is not actually setting the ignore_host flag but polling for one or more system SNMP OID's which as you rightly pointed out flags the current_host->ignore_host as true.  There are also several other paths that force the same issue.

However, if the system is unable to retrieve the device SNMP generic data, I think it should be ignoring the reindexing because if it failed for the basic data, it would more than likely also fail for the larger data.  Since we want to ensure that timeouts are minimised, we don't really want to be trying to have repeated calls for SNMP data were it's not responding.

Besides, even if we prevented the get_system_information call, the next part which starts the reindexing will more than likely fail on the first SNMP call and then just skip rest anyway.  So effectively, it just doubles up on a timeout without giving any benefit.

Based of your comment above, we should probably not be even initialising the session data at line 504 - 519.  If you can provide any more insight to that, I'll be happy to take that on board but so far, I am not seeing how this change would help but that could just be because i'm rushing through this on my lunch hour.

**Comment by cigamit** [comment]
Spine behaves quite a bit different than cmd.php, and I've been meaning to convert cmd.php to be more like spine, but it's never really been a priority.  When spine operates, it looks for hosts that have the hostname of 'localhost', and if that is found, it's a special case.

However, if your snmp queries are listed as 'uptime goes backwards', then that might be race condition, since that re-index method assumes snmp presently.  When a device does not respond to snmp, the device is immediately ignored for the remainder of the polling cycle to allow cacti to scale horizontally by the number of devices.  This is another difference between spine and cmd.php, and one of the reasons spine is a bit more efficient.

However, re-reading you comments, there may be a bug introduced as you stated.  I'll take a look.

**Comment by cigamit** [comment]
Resolved.
