### ISSUE TITLE
Number of threads is taken from poller table of mysql

### ISSUE THREAD

**Issue by nkozubsky** [Cacti/spine#59]
We have a value "max_threads" of settings table. Why we take getpsetting(&mysql, "threads") from poller table? (in util.c file) The "threads" value from poller table is not changible by web.
What you think about return to 1.1.38 in this place of util.c file ?

FROM NEW
/* get Cacti defined max threads override spine.conf */
        if ((res = getpsetting(&mysql, "threads")) != 0) {

TO OLD
/* get Cacti defined max threads override spine.conf */
        if ((res = getsetting(&mysql, "max_threads")) != 0) {

and delete getpsetting function at all.

The spine has one only thread now. (w/o manual changed "threads" field of "poller" table)

Please check me!

**Comment by netniV** [comment]
OK so that has cleared a lot of things up for me in one go.  The reason is that under 1.2 we define the maximum number of threads by the poller itself.  So, this allows a way to customise the number of processes and threads per collector as each may be running on a different set of (virtual/physical) hardware.

Thanks to the forum post, I realised what was going on.  So, if you are using a 1.2 version of spine, it expects the value to be against the poller as that's where it will set in 1.2 of cacti.  If you are using a 1.2 version of spine against a 1.1.38 version of cacti, you will NOT be able to set the number of threads without going to to the DB directly.

Under 1.2, to edit, goto Console -> Data Collections -> Data Collectors -> Edit Data Collector (by clicking on one).

**Comment by netniV** [comment]
In fact, there is already an outstanding issue of #52 which is probably related.

**Comment by netniV** [comment]
I believe that the core #1674 issue is the real reason for the problem.  As such, I am going to close this issue now.  If you believe that this is in error please let me know why.
