### ISSUE TITLE
v1.2.3 download on cacti.net has not been bootstrapped

### ISSUE THREAD

**Issue by KnoAll** [Cacti/spine#89]
**Describe the bug**
in previous releases bootstrap has already been done, this is not the case in 1.2.3 download. Is this intentional?

**To Reproduce**
download 1.2.3 from cacti.net
https://www.cacti.net/downloads/spine/cacti-spine-1.2.3.tar.gz

**Expected behavior**
should contain configure but does not.

**Comment by netniV** [comment]
As far as I am aware, bootstrapping should only occur on the destination system.

**Comment by KnoAll** [comment]
Understood. Just checking as 'configure' has been there on all other releases I checked, and has worked for me every time. (without having to bootstrap)

**Comment by netniV** [comment]
I think that was a mistake in the past because the documentation even states that you run bootstrap, not configure (the bootstrap process does run configure I believe).  If a newer version of configure/m4 is used and placed in the archive, it creates a problem for older systems.

Thanks for querying it though and noticing the change!
